name: nabi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #core
  stacked:
  stacked_services:
  stacked_shared:

  #network
  
  dio: ^5.4.0
  json_annotation: ^4.9.0

  #ui
  glass_kit: ^4.0.2
  dotted_border: ^2.1.0
  camera: ^0.10.6
  flutter_svg: ^1.1.6
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  flutter_gen: ^5.4.0
  image_picker: ^1.0.7
  pinput: ^5.0.0
  flutter_otp_text_field: ^1.2.0
  flutter_countdown_timer: ^4.1.0
  intl_phone_number_input:
    #path: ../../segun/intl_phone_number_input
    git:
      url: https://github.com/Shek863/intl_phone_number_input.git
      ref: koolika
  mapbox_search: ^3.2.0
  mapbox_maps_flutter: ^2.12.0
  geolocator: ^14.0.2

  #utils
  #flutter_libphonenumber: ^2.5.1
  dlibphonenumber: ^1.1.35
  url_launcher: ^6.2.5
  double_back_to_close: ^2.0.0
  email_validator: ^2.1.17
  encrypt: ^5.0.3
  flutter_arb_translator: ^1.0.8
  intl: ^0.20.2
  connectivity_plus: ^6.0.3
  #kkiapay_flutter_sdk:
  shimmer_animation: ^2.1.0
  flutter_local_notifications: ^18.0.1

  #storage
  permission_handler: ^11.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.6.1
  golden_toolkit: ^0.15.0
  #flutter_gen_runner:
  hive_generator: ^2.0.1
  # retrofit_generator:
  # built_value_generator:
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - .env
    #png
    - assets/png/
    # svg
    - assets/svg/
    - assets/svg/flag/

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/CenturyGothic-bold.ttf
          weight: 700
        - asset: assets/fonts/CenturyGothic.ttf
          weight: 500
